
version: 2.1

orbs:
  node: circleci/node@4.1


jobs: 
  build-and-test:  
   docker:
      - image: circleci/node:14.17.0
   steps:
      - checkout
      - run:
          command: yarn add -E serverless
      - run:
          command: yarn install      
      - run:
          command: ./.circleci/install-credentials.sh
      - run: 
          command: sls deploy

workflows:
  build-and-test: 
    jobs:
      - build-and-test:
          context: serverlessProject
